apiVersion: v1
kind: ConfigMap
metadata:
  name: github-token-minter-config
  namespace: agent-system
data:
  YOUR_GITHUB_ORG-YOUR_GITHUB_REPO.yaml: |
    version: 'minty.abcxyz.dev/v2'
    rule:
      if: "assertion.iss == 'https://container.googleapis.com/v1/projects/YOUR_PROJECT_ID/locations/YOUR_REGION/clusters/YOUR_CLUSTER'"
    scope:
      platform-agent-scope:
        rule:
          if: "assertion.sub == 'system:serviceaccount:agent-system:platform-agent'"
        repositories:
          - 'YOUR_GITHUB_REPO'
        permissions:
          contents: 'write'
          pull_requests: 'write'
