apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-token-minter-ksa
  namespace: agent-system
  annotations:
    iam.gke.io/gcp-service-account: github-token-minter-sa@YOUR_PROJECT_ID.iam.gserviceaccount.com
automountServiceAccountToken: false
