name: Autopush Redeploy Controller

on:
  workflow_run:
    workflows: ["Publish Controller to GHCR"]
    types:
      - completed

concurrency:
  group: autopush-redeploy-controller
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  call-deploy:
    if: |
      github.repository == 'gke-labs/kube-agents' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    uses: ./.github/workflows/reusable-deploy-controller.yml
    with:
      target_environment: "autopush"
      controller_tag: ${{ github.event.workflow_run.head_sha }}
      checkout_ref: ${{ github.event.workflow_run.head_sha }}
