name: Staging Redeploy Integrations

on:
  push:
    tags:
      - "staging/**"

concurrency:
  group: staging-redeploy-integrations
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  call-deploy:
    secrets: inherit
    uses: ./.github/workflows/reusable-deploy-integrations.yml
    with:
      target_environment: "staging"
      force_deploy: true
      checkout_ref: ${{ github.ref }}
